name: Create releases
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: release
    if: github.ref == 'refs/heads/main' && github.repository == 'openai/openai-ruby'
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: stainless-api/trigger-release-please@v1
        id: release
        with:
          repo: ${{ github.event.repository.full_name }}
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Set up Ruby
	if: ${{ steps.release.outputs.releases_created }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          ruby-version: '3.1'
      - run: |-
          bundle install

      - name: Publish to RubyGems.org
	if: ${{ steps.release.outputs.releases_created }}
        run: |
          bash ./bin/publish-gem
        env:
          # `RUBYGEMS_HOST` is only required for private gem repositories, not https://rubygems.org
          RUBYGEMS_HOST: ${{ secrets.OPENAI_RUBYGEMS_HOST || secrets.RUBYGEMS_HOST }}
          GEM_HOST_API_KEY: ${{ secrets.OPENAI_GEM_HOST_API_KEY || secrets.GEM_HOST_API_KEY }}
